Repository What-Today-FE/What-Today, pull requests merged in 2025-08, with the labels that each got.

#183 체험 등록/수정 API 연결
  apps/what-today/src/apis/experiences.ts
  apps/what-today/src/components/activities/ActivitiesInformation.tsx
  apps/what-today/src/components/experiences/CategorySelect.tsx
  apps/what-today/src/components/experiences/DescriptionTextarea.tsx
  apps/what-today/src/components/experiences/ImageInput.tsx
  apps/what-today/src/components/experiences/PriceInput.tsx
  apps/what-today/src/components/experiences/ScheduleInput.tsx
  apps/what-today/src/components/experiences/TitleInput.tsx
  apps/what-today/src/hooks/useMyActivitiesQuery.ts
  apps/what-today/src/pages/activities/index.tsx
  apps/what-today/src/pages/experiences/index.tsx
  apps/what-today/src/pages/mypage/manage-activities/index.tsx
  apps/what-today/src/schemas/experiences.ts
  packages/design-system/src/components/DatePicker.tsx
  packages/design-system/src/components/ExperienceCard.tsx
  packages/design-system/src/components/TimePicker.tsx
  packages/design-system/src/components/addressInput/AddressInput.tsx
  packages/design-system/src/components/addressInput/types/index.ts
  packages/design-system/src/components/input/InputField.tsx
  packages/design-system/src/components/input/InputTextarea.tsx
  packages/design-system/src/components/input/InputWrapper.tsx
  packages/design-system/src/components/popover/PopoverRoot.tsx
  packages/design-system/src/components/popover/PopoverTrigger.tsx
  packages/design-system/src/components/popover/types/index.ts
  packages/design-system/src/components/select/SelectRoot.tsx
  packages/design-system/src/components/select/SelectTrigger.tsx
  packages/design-system/src/components/select/SelectValue.tsx
  packages/design-system/src/components/select/types/index.ts
  packages/design-system/src/pages/InputDoc.tsx
  packages/design-system/src/pages/SelectDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: ♻️ Refactor, ✨ Feat, 🎨 Design, 📮 Api

#190 메인페이지 QA반영
  apps/what-today/src/pages/main/index.tsx
  packages/design-system/src/components/Footer.tsx
  packages/design-system/src/components/MainSearchInput/MainSearchInput.tsx
  packages/design-system/src/components/RadioGroup/RadioGroup.tsx
Labels: ♻️ Refactor

#191 체험 상세페이지 로그인 상태 기반 조건부 기능 구현
  apps/what-today/src/components/activities/ActivitiesInformation.tsx
  apps/what-today/src/components/activities/ReservationBottomBar.tsx
  apps/what-today/src/components/activities/reservation/DesktopReservation.tsx
  apps/what-today/src/components/activities/reservation/MobileReservationSheet.tsx
  apps/what-today/src/components/activities/reservation/ReservationForm.tsx
  apps/what-today/src/components/activities/reservation/TabletReservationSheet.tsx
  apps/what-today/src/components/activities/reservation/types/index.ts
  apps/what-today/src/pages/activities/index.tsx
Labels: ♻️ Refactor, ✨ Feat

#194 404 에러 페이지
  apps/what-today/src/pages/not-found-page/index.tsx
  apps/what-today/src/routes/index.tsx
  packages/design-system/src/components/logos/NotFoundLogo.tsx
  packages/design-system/src/components/logos/index.ts
  packages/design-system/src/pages/LogoDoc.tsx
Labels: ✨ Feat

#209 마이 - 메인페이지의 컴포넌트 UI 제작
  packages/design-system/src/components/MypageProfileHeader.tsx
  packages/design-system/src/components/MypageSummaryCard.tsx
  packages/design-system/src/components/OngoingExperienceCard.tsx
  packages/design-system/src/components/UpcomingSchedule.tsx
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/pages/MypageProfileHeaderDoc.tsx
  packages/design-system/src/pages/MypageSummaryCardDoc.tsx
  packages/design-system/src/pages/OngoingExperienceCardDoc.tsx
  packages/design-system/src/pages/UpcomingScheduleDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: 🎨 Design

#196 예약내역 라디오 수정, 예약카드 줄바꿈 수정
  apps/what-today/src/pages/mypage/reservations-list/index.tsx
  packages/design-system/src/components/ReservationCard.tsx
Labels: ♻️ Refactor

#207 페이지 번역 기능 도입
  apps/what-today/package.json
  apps/what-today/src/components/FlagIcon.tsx
  apps/what-today/src/components/FloatingTranslateButton.tsx
  apps/what-today/src/constants/.gitkeep
  apps/what-today/src/constants/languages.ts
  apps/what-today/src/index.css
  apps/what-today/src/layouts/DefaultLayout.tsx
  apps/what-today/src/vite-env.d.ts
Labels: ✨ Feat, 📮 Api

#201 카카오 로그인 403 에러 처리
  apps/what-today/src/hooks/useKakaoOAuth.ts
Labels: 🐞 Bug

#204 회원가입시 약관 동의 추가
  apps/what-today/src/components/auth/AgreeCheckbox.tsx
  apps/what-today/src/components/auth/AgreeContent.tsx
  apps/what-today/src/pages/signup/index.tsx
  apps/what-today/src/schemas/auth.ts
Labels: ✨ Feat

#215 메인페이지 카드 개수 수정
  apps/what-today/src/pages/main/index.tsx
  packages/design-system/src/components/Carousel/MobileCarousel.tsx
  packages/design-system/src/components/MainCard/Image.tsx
Labels: ♻️ Refactor

#205 예약 현황 페이지 리팩토링(+체험등록 페이지 hook 수정)
  apps/what-today/src/apis/myActivities.ts
  apps/what-today/src/components/activities/ActivitiesInformation.tsx
  apps/what-today/src/components/reservations-status/ReservationCalendar.tsx
  apps/what-today/src/components/reservations-status/ReservationSheet.tsx
  apps/what-today/src/hooks/myActivity/useDeleteMyActivityMutation.ts
  apps/what-today/src/hooks/myActivity/useMyActivitiesQuery.ts
  apps/what-today/src/hooks/myReservation/useDailyScheduleQuery.ts
  apps/what-today/src/hooks/myReservation/useMonthlyScheduleQuery.ts
  apps/what-today/src/hooks/myReservation/useReservationQuery.ts
  apps/what-today/src/hooks/useMyActivitiesQuery.ts
  apps/what-today/src/pages/mypage/manage-activities/index.tsx
  apps/what-today/src/pages/mypage/reservations-status/index.tsx
  packages/design-system/src/components/calendar/CalendarRoot.tsx
Labels: ♻️ Refactor, 📮 Api

#214 알림 캐싱 오류 해결 & 반복 일정 추가 기능 구현
  apps/what-today/src/components/experiences/DescriptionTextarea.tsx
  apps/what-today/src/components/experiences/RecurringScheduleModal.tsx
  apps/what-today/src/components/experiences/ScheduleInput.tsx
  apps/what-today/src/components/notification/NotificationPopover.tsx
  apps/what-today/src/pages/experiences/index.tsx
  apps/what-today/src/routes/index.tsx
  packages/design-system/src/components/DatePicker.tsx
  packages/design-system/src/components/popover/PopoverRoot.tsx
  packages/design-system/src/pages/MypageProfileHeaderDoc.tsx
  packages/design-system/src/pages/MypageSummaryCardDoc.tsx
  packages/design-system/src/pages/OngoingExperienceCardDoc.tsx
  packages/design-system/src/pages/UpcomingScheduleDoc.tsx
Labels: ✨ Feat, 🐞 Bug

#213 예약 내역 페이지 QA 내용 수정
  apps/what-today/src/pages/mypage/reservations-list/index.tsx
  packages/design-system/src/components/StarRating.tsx
Labels: ♻️ Refactor, 🐞 Bug, 🎨 Design

#223 라디오 애니메이션 제거
  packages/design-system/src/components/RadioGroup/RadioGroup.tsx
Labels: ♻️ Refactor

#229 메인페이지 스켈레톤 구현
  apps/what-today/src/pages/main/index.tsx
  packages/design-system/src/components/Carousel/Carousel.tsx
  packages/design-system/src/components/MainPageSkeleton/MainPageSkeleton.tsx
  packages/design-system/src/components/MainPageSkeleton/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/layouts/Sidebar.tsx
  packages/design-system/src/pages/MainPageSkeletonDoc.tsx
  packages/design-system/src/routes/index.tsx
Labels: ✨ Feat

#231 체험관리, 예약 현황 페이지 토스트 구현 / 캘린더 뱃지 실시간 반영
  apps/what-today/src/components/reservations-status/ReservationSheet.tsx
  apps/what-today/src/pages/mypage/manage-activities/index.tsx
  apps/what-today/src/pages/mypage/reservations-status/index.tsx
Labels: ✨ Feat

#232 체험 상세페이지 UI 리팩토링
  apps/what-today/src/components/activities/ActivitiesDescription.tsx
  apps/what-today/src/components/activities/ActivitiesInformation.tsx
  apps/what-today/src/components/activities/ActivitiesMap.tsx
  apps/what-today/src/components/activities/ActivitiesReview.tsx
  apps/what-today/src/components/activities/ActivityImages.tsx
  apps/what-today/src/components/activities/Divider.tsx
  apps/what-today/src/components/activities/ReservationBottomBar.tsx
  apps/what-today/src/components/activities/ReviewSection.tsx
  apps/what-today/src/components/activities/reservation/HeadCountSelector.tsx
  apps/what-today/src/components/activities/reservation/MobileReservationSheet.tsx
  apps/what-today/src/components/activities/reservation/ReservationForm.tsx
  apps/what-today/src/components/activities/reservation/TabletReservationSheet.tsx
  apps/what-today/src/components/activities/reservation/TimeSelector.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesDescriptionSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesInformationSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesMapSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivityDetailPageSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivityImagesSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/DividerSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReservationFormSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReviewCardSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReviewSectionSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/index.ts
  apps/what-today/src/pages/activities/index.tsx
Labels: ♻️ Refactor, 🎨 Design

#247 가격 Input에 문자가 적히는 오류 해결 & 천 단위로 쉼표 추가
  apps/what-today/src/components/experiences/PriceInput.tsx
  apps/what-today/src/pages/experiences/index.tsx
Labels: ♻️ Refactor, 🐞 Bug

#249 예약 내역 페이지 버그수정 및 스켈레톤 UI 추가
  apps/what-today/src/components/skeletons/index.ts
  apps/what-today/src/components/skeletons/reservations-list/ReservationCardSkeleton.tsx
  apps/what-today/src/components/skeletons/reservations-list/ReservationsListPageSkeleton.tsx
  apps/what-today/src/components/skeletons/reservations-list/index.ts
  apps/what-today/src/pages/mypage/reservations-list/index.tsx
  apps/what-today/src/schemas/myReservations.ts
Labels: ♻️ Refactor, 🎨 Design, 📮 Api

#253 Footer UI 리팩토링
  packages/design-system/src/components/Footer.tsx
  packages/design-system/src/components/icons/DesignIcon.tsx
  packages/design-system/src/components/icons/index.ts
Labels: ♻️ Refactor, 🎨 Design

#257 체험 상세페이지 추가 디자인 수정
  apps/what-today/src/components/activities/ActivitiesInformation.tsx
  apps/what-today/src/components/activities/ActivitiesReview.tsx
  apps/what-today/src/components/activities/ReservationBottomBar.tsx
  apps/what-today/src/components/activities/ReviewSection.tsx
  apps/what-today/src/components/activities/reservation/HeadCountSelector.tsx
  apps/what-today/src/components/activities/reservation/MobileReservationSheet.tsx
  apps/what-today/src/components/activities/reservation/ReservationForm.tsx
  apps/what-today/src/components/activities/reservation/TabletReservationSheet.tsx
  apps/what-today/src/pages/activities/index.tsx
Labels: ♻️ Refactor, 🎨 Design

#264 컴포넌트 shadow 추가
  apps/what-today/src/components/activities/ActivitiesReview.tsx
  apps/what-today/src/components/notification/NotificationPopover.tsx
  apps/what-today/src/components/reservations-status/ReservationCalendar.tsx
  apps/what-today/src/pages/main/index.tsx
  packages/design-system/src/components/Carousel/NavigationButton.tsx
  packages/design-system/src/components/DatePicker.tsx
  packages/design-system/src/components/select/SelectContent.tsx
Labels: ✨ Feat

#266 배너 이미지 수정
  packages/design-system/src/components/MainBanner/dummyBanners.ts
Labels: ✨ Feat

#267 DefaultLayout 통일하기
  apps/what-today/src/components/FloatingTranslateButton.tsx
  apps/what-today/src/components/MypageSidebar.tsx
  apps/what-today/src/layouts/DefaultLayout.tsx
  apps/what-today/src/layouts/Mypage.tsx
  apps/what-today/src/pages/activities/index.tsx
  packages/design-system/src/components/Footer.tsx
Labels: 🎨 Design

#270 예약 내역 페이지 이슈 QA
  apps/what-today/src/pages/mypage/reservations-list/index.tsx
Labels: ♻️ Refactor, 🎨 Design

#274 토스트 메세지 통합 및 UI 수정 및 불필요한 파일 삭제
  apps/what-today/src/assets/icons/.gitkeep
  apps/what-today/src/assets/images/.gitkeep
  apps/what-today/src/components/activities/mockReviews.ts
  apps/what-today/src/components/notification/NotificationPopover.tsx
  apps/what-today/src/components/notification/mock-notifications-pages.json
  apps/what-today/src/pages/experiences/index.tsx
  apps/what-today/src/pages/mypage/reservations-list/index.tsx
  apps/what-today/src/stores/.gitkeep
  apps/what-today/src/utils/.gitkeep
  packages/design-system/src/assets/images/.gitkeep
  packages/design-system/src/components/Footer.tsx
Labels: ♻️ Refactor, 🎨 Design

#278 OG 매타태그 설정
  apps/what-today/index.html
  apps/what-today/public/og-image.webp
Labels: 📦 Chore

#279 스켈레톤 색상 통일
  apps/what-today/src/components/FloatingTranslateButton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesDescriptionSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesInformationSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesMapSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivityDetailPageSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivityImagesSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/DividerSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReservationFormSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReviewCardSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReviewSectionSkeleton.tsx
  apps/what-today/src/components/skeletons/reservations-list/ReservationCardSkeleton.tsx
  apps/what-today/src/components/skeletons/reservations-list/ReservationsListPageSkeleton.tsx
Labels: 🎨 Design

#280 v.4
  apps/what-today/index.html
  apps/what-today/public/og-image.webp
  apps/what-today/src/components/FloatingTranslateButton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesDescriptionSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesInformationSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivitiesMapSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivityDetailPageSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ActivityImagesSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/DividerSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReservationFormSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReviewCardSkeleton.tsx
  apps/what-today/src/components/skeletons/activities/ReviewSectionSkeleton.tsx
  apps/what-today/src/components/skeletons/reservations-list/ReservationCardSkeleton.tsx
  apps/what-today/src/components/skeletons/reservations-list/ReservationsListPageSkeleton.tsx
Labels: 🌐 Deploy

#283 체험 수정이 안되는 오류 해결
  apps/what-today/src/pages/experiences/index.tsx
Labels: 🐞 Bug

#281 리드미 작성
  README.md
  apps/what-today/public/Jiseob.png
  apps/what-today/public/Jiwoo.png
  apps/what-today/public/image.png
  apps/what-today/public/image2.png
  apps/what-today/public/image3.png
  apps/what-today/public/image4.png
  apps/what-today/public/jihyun.png
  apps/what-today/public/taeil.png
Labels: 📝 Docs
